# Generated by Django 3.0.7 on 2020-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200606_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='/media/photos/Article.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
