# Generated by Django 3.0.7 on 2020-06-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200609_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='media/photos/Article.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
