# Generated by Django 3.0.7 on 2020-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200609_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='photos/Article.jpg', height_field=200, upload_to='photos/%Y/%m/%d/', width_field=200),
        ),
    ]
